import 'package:dijital_kitap/providers/book.dart';
import 'package:flutter/material.dart';

class Books with ChangeNotifier {
  List<Book> get books => [...bookList];

  List<Book> get getFavorites =>
      bookList.where((element) => element.isFavorite).toList();

  List<Book> bookList = [
    Book(
      id: 1,
      authorFirstName: "Caro",
      authorLastName: "Blase",
      description:
          "Strain of extensor muscle, fascia and tendon of left index finger at forearm level",
      date: "7/18/2010",
      categories: "thriller",
      authorGender: "Female",
      authorAge: 23,
      avatar:
          "https://robohash.org/liberofacereminima.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 2,
      authorFirstName: "Briny",
      authorLastName: "Beckwith",
      description:
          "Unspecified injury of intrinsic muscle, fascia and tendon of other finger at wrist and hand level, sequela",
      date: "11/29/2018",
      categories: "history",
      authorGender: "Female",
      authorAge: 12,
      avatar: "https://robohash.org/quiutconsequatur.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 3,
      authorFirstName: "Hilton",
      authorLastName: "Pinson",
      description: "Stress fracture, unspecified toe(s)",
      date: "1/2/2013",
      categories: "fiction",
      authorGender: "Male",
      authorAge: 71,
      avatar: "https://robohash.org/quiaquamporro.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 4,
      authorFirstName: "Morgen",
      authorLastName: "Siddall",
      description:
          "Poisoning by other drug primarily affecting the autonomic nervous system, assault, initial encounter",
      date: "7/23/2012",
      categories: "sci-fi",
      authorGender: "Male",
      authorAge: 58,
      avatar:
          "https://robohash.org/praesentiumadipisciconsectetur.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 5,
      authorFirstName: "Noland",
      authorLastName: "Armour",
      description:
          "Displaced supracondylar fracture without intracondylar extension of lower end of left femur, subsequent encounter for closed fracture with routine healing",
      date: "12/30/2015",
      categories: "sci-fi",
      authorGender: "Male",
      authorAge: 31,
      avatar: "https://robohash.org/ipsamdolorvel.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 6,
      authorFirstName: "Kile",
      authorLastName: "Valente",
      description: "Toxic effect of ketones, undetermined, initial encounter",
      date: "4/11/2002",
      categories: "utopia",
      authorGender: "Male",
      authorAge: 39,
      avatar:
          "https://robohash.org/beataenesciuntdolore.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 7,
      authorFirstName: "Gisela",
      authorLastName: "Crannell",
      description: "Other bursal cyst, ankle and foot",
      date: "2/7/2013",
      categories: "romance",
      authorGender: "Female",
      authorAge: 32,
      avatar:
          "https://robohash.org/delenitiodioprovident.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 8,
      authorFirstName: "Patty",
      authorLastName: "Utley",
      description:
          "Chronic venous hypertension (idiopathic) with other complications of left lower extremity",
      date: "2/8/2002",
      categories: "utopia",
      authorGender: "Male",
      authorAge: 27,
      avatar: "https://robohash.org/utullamvoluptas.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 9,
      authorFirstName: "Anselma",
      authorLastName: "Berridge",
      description:
          "Nondisplaced comminuted supracondylar fracture without intercondylar fracture of right humerus, initial encounter for open fracture",
      date: "8/30/2013",
      categories: "history",
      authorGender: "Female",
      authorAge: 29,
      avatar: "https://robohash.org/eteumculpa.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 10,
      authorFirstName: "Symon",
      authorLastName: "Nuss",
      description:
          "Ulcerative (chronic) proctitis with unspecified complications",
      date: "11/2/2019",
      categories: "fiction",
      authorGender: "Male",
      authorAge: 81,
      avatar: "https://robohash.org/doloribusutet.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 11,
      authorFirstName: "Berna",
      authorLastName: "Inglish",
      description: "Laceration of unspecified blood vessel of thorax",
      date: "2/20/2020",
      categories: "history",
      authorGender: "Female",
      authorAge: 32,
      avatar: "https://robohash.org/nonofficiaaut.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 12,
      authorFirstName: "Meyer",
      authorLastName: "Griston",
      description: "Unspecified transplanted organ and tissue rejection",
      date: "4/28/2019",
      categories: "utopia",
      authorGender: "Male",
      authorAge: 63,
      avatar: "https://robohash.org/eaerrorest.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 13,
      authorFirstName: "Sidonnie",
      authorLastName: "Castles",
      description: "Other synovitis and tenosynovitis, right thigh",
      date: "11/1/2009",
      categories: "fiction",
      authorGender: "Female",
      authorAge: 12,
      avatar:
          "https://robohash.org/rerummagnimaiores.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 14,
      authorFirstName: "Homerus",
      authorLastName: "Salery",
      description:
          "Pathological fracture, pelvis, subsequent encounter for fracture with nonunion",
      date: "3/21/2015",
      categories: "utopia",
      authorGender: "Male",
      authorAge: 5,
      avatar: "https://robohash.org/quaerateossed.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 15,
      authorFirstName: "Pip",
      authorLastName: "Cottey",
      description: "Nutritional deficiency, unspecified",
      date: "3/16/2013",
      categories: "history",
      authorGender: "Male",
      authorAge: 41,
      avatar: "https://robohash.org/magnienimvel.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 16,
      authorFirstName: "Jory",
      authorLastName: "Cardinale",
      description: "Corrosion of second degree of forearm",
      date: "9/15/2018",
      categories: "romance",
      authorGender: "Male",
      authorAge: 27,
      avatar: "https://robohash.org/placeatillumut.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 17,
      authorFirstName: "Virginia",
      authorLastName: "Fancott",
      description:
          "Nondisplaced fracture of shaft of unspecified metacarpal bone",
      date: "5/6/2015",
      categories: "fiction",
      authorGender: "Female",
      authorAge: 41,
      avatar:
          "https://robohash.org/quamaperiamtempora.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 18,
      authorFirstName: "Rhianna",
      authorLastName: "Parslow",
      description: "Assault by paintball gun discharge, sequela",
      date: "11/10/2012",
      categories: "thriller",
      authorGender: "Female",
      authorAge: 29,
      avatar: "https://robohash.org/quoquicommodi.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 19,
      authorFirstName: "Rupert",
      authorLastName: "Rolland",
      description: "Radial collateral ligament sprain",
      date: "1/11/2009",
      categories: "history",
      authorGender: "Male",
      authorAge: 74,
      avatar:
          "https://robohash.org/doloresquonesciunt.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 20,
      authorFirstName: "Marsh",
      authorLastName: "Quadrio",
      description: "Varus deformity, not elsewhere classified, left ankle",
      date: "9/28/2016",
      categories: "sci-fi",
      authorGender: "Male",
      authorAge: 35,
      avatar: "https://robohash.org/dolornonin.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 21,
      authorFirstName: "Dougy",
      authorLastName: "Eberst",
      description:
          "Infection and inflammatory reaction due to implanted electronic neurostimulator of peripheral nerve, electrode (lead), initial encounter",
      date: "10/25/2017",
      categories: "romance",
      authorGender: "Male",
      authorAge: 17,
      avatar:
          "https://robohash.org/recusandaesuscipitnon.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 22,
      authorFirstName: "Eugenio",
      authorLastName: "Goodliff",
      description:
          "Nondisplaced midcervical fracture of unspecified femur, subsequent encounter for closed fracture with malunion",
      date: "7/17/2016",
      categories: "romance",
      authorGender: "Male",
      authorAge: 62,
      avatar:
          "https://robohash.org/necessitatibusquoaperiam.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 23,
      authorFirstName: "Marten",
      authorLastName: "Wyldbore",
      description:
          "Complete traumatic transmetacarpal amputation of unspecified hand, sequela",
      date: "10/7/2013",
      categories: "romance",
      authorGender: "Male",
      authorAge: 62,
      avatar:
          "https://robohash.org/quoplaceataperiam.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 24,
      authorFirstName: "Timmy",
      authorLastName: "Brendel",
      description:
          "Toxic effect of venom of black widow spider, accidental (unintentional)",
      date: "2/15/2009",
      categories: "history",
      authorGender: "Male",
      authorAge: 76,
      avatar:
          "https://robohash.org/architectoquineque.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 25,
      authorFirstName: "Tab",
      authorLastName: "Gages",
      description:
          "Other generalized epilepsy and epileptic syndromes, not intractable",
      date: "10/26/2016",
      categories: "history",
      authorGender: "Male",
      authorAge: 13,
      avatar:
          "https://robohash.org/voluptatumdolorumvoluptatem.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 26,
      authorFirstName: "Gregorius",
      authorLastName: "Mangan",
      description: "Disorders of fatty-acid metabolism",
      date: "5/30/2007",
      categories: "mistery",
      authorGender: "Male",
      authorAge: 35,
      avatar: "https://robohash.org/sedmolestiasquis.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 27,
      authorFirstName: "Tallie",
      authorLastName: "Guiraud",
      description:
          "Partial traumatic amputation of right forearm, level unspecified, subsequent encounter",
      date: "12/19/2015",
      categories: "thriller",
      authorGender: "Female",
      authorAge: 100,
      avatar: "https://robohash.org/placeatsuntut.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 28,
      authorFirstName: "Eberto",
      authorLastName: "Wimms",
      description: "Retinal hemorrhage, right eye",
      date: "3/20/2005",
      categories: "sci-fi",
      authorGender: "Male",
      authorAge: 25,
      avatar: "https://robohash.org/magnametdebitis.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 29,
      authorFirstName: "Karoline",
      authorLastName: "Maple",
      description: "Stress fracture, left ulna, initial encounter for fracture",
      date: "12/17/2013",
      categories: "romance",
      authorGender: "Female",
      authorAge: 70,
      avatar: "https://robohash.org/totamquiodit.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 30,
      authorFirstName: "Shaine",
      authorLastName: "Kirckman",
      description: "Injury of unspecified intra-abdominal organ",
      date: "4/9/2017",
      categories: "history",
      authorGender: "Female",
      authorAge: 99,
      avatar: "https://robohash.org/quibusdamautqui.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 31,
      authorFirstName: "Miguela",
      authorLastName: "Sandon",
      description: "Nursemaid's elbow, left elbow",
      date: "1/18/2017",
      categories: "thriller",
      authorGender: "Female",
      authorAge: 35,
      avatar:
          "https://robohash.org/etmolestiaeplaceat.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 32,
      authorFirstName: "Sascha",
      authorLastName: "Lockett",
      description: "Encounter for surveillance of contraceptives, unspecified",
      date: "8/1/2004",
      categories: "fiction",
      authorGender: "Male",
      authorAge: 99,
      avatar:
          "https://robohash.org/suscipitdoloremvoluptates.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 33,
      authorFirstName: "Neal",
      authorLastName: "Larkkem",
      description:
          "Person boarding or alighting a motorcycle injured in collision with two- or three-wheeled motor vehicle, subsequent encounter",
      date: "9/8/2010",
      categories: "mistery",
      authorGender: "Male",
      authorAge: 20,
      avatar:
          "https://robohash.org/beataeconsequaturlabore.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 34,
      authorFirstName: "Meghann",
      authorLastName: "Furst",
      description: "Low-tension glaucoma, right eye",
      date: "6/7/2017",
      categories: "thriller",
      authorGender: "Female",
      authorAge: 66,
      avatar: "https://robohash.org/atfacilisearum.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 35,
      authorFirstName: "Carter",
      authorLastName: "Topham",
      description:
          "Asphyxiation due to being trapped in other low oxygen environment, sequela",
      date: "11/19/2000",
      categories: "mistery",
      authorGender: "Male",
      authorAge: 73,
      avatar: "https://robohash.org/quinonquasi.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 36,
      authorFirstName: "Tansy",
      authorLastName: "Heyfield",
      description:
          "Dependence on enabling machines and devices, not elsewhere classified",
      date: "12/11/2006",
      categories: "romance",
      authorGender: "Female",
      authorAge: 75,
      avatar: "https://robohash.org/nisivelaperiam.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 37,
      authorFirstName: "Liz",
      authorLastName: "Vincent",
      description:
          "Car passenger injured in collision with fixed or stationary object in traffic accident",
      date: "12/25/2018",
      categories: "thriller",
      authorGender: "Female",
      authorAge: 22,
      avatar: "https://robohash.org/sedquaeratrerum.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 38,
      authorFirstName: "Sigmund",
      authorLastName: "Newham",
      description:
          "Displaced fracture of coronoid process of unspecified ulna, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing",
      date: "10/11/2009",
      categories: "thriller",
      authorGender: "Male",
      authorAge: 88,
      avatar:
          "https://robohash.org/providentnobisblanditiis.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 39,
      authorFirstName: "Willamina",
      authorLastName: "Hallowes",
      description: "Injury of unspecified body region",
      date: "2/27/2020",
      categories: "fiction",
      authorGender: "Female",
      authorAge: 49,
      avatar:
          "https://robohash.org/inventoreerrorsoluta.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 40,
      authorFirstName: "Cyrille",
      authorLastName: "Helmke",
      description: "Myositis ossificans traumatica, hand",
      date: "11/8/2006",
      categories: "romance",
      authorGender: "Male",
      authorAge: 74,
      avatar:
          "https://robohash.org/reprehenderitquiain.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 41,
      authorFirstName: "Abbie",
      authorLastName: "Ahren",
      description:
          "Blister (nonthermal) of breast, right breast, subsequent encounter",
      date: "3/22/2006",
      categories: "thriller",
      authorGender: "Male",
      authorAge: 26,
      avatar:
          "https://robohash.org/voluptatumdignissimosincidunt.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 42,
      authorFirstName: "Christal",
      authorLastName: "Atterley",
      description:
          "Nondisplaced transverse fracture of shaft of unspecified tibia, subsequent encounter for closed fracture with nonunion",
      date: "5/10/2011",
      categories: "sci-fi",
      authorGender: "Female",
      authorAge: 80,
      avatar: "https://robohash.org/quoseterror.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 43,
      authorFirstName: "Devan",
      authorLastName: "Dressel",
      description:
          "Driver of pick-up truck or van injured in collision with unspecified motor vehicles in nontraffic accident",
      date: "4/10/2008",
      categories: "thriller",
      authorGender: "Female",
      authorAge: 51,
      avatar:
          "https://robohash.org/estreprehenderitvoluptatem.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 44,
      authorFirstName: "Lydie",
      authorLastName: "Leighton",
      description: "Postradiation scoliosis",
      date: "2/4/2005",
      categories: "sci-fi",
      authorGender: "Female",
      authorAge: 1,
      avatar: "https://robohash.org/nisisuntdebitis.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 45,
      authorFirstName: "Jerry",
      authorLastName: "Schaben",
      description:
          "Corrosion of first degree of unspecified multiple fingers (nail), not including thumb, initial encounter",
      date: "10/12/2002",
      categories: "romance",
      authorGender: "Male",
      authorAge: 51,
      avatar: "https://robohash.org/iurequout.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 46,
      authorFirstName: "Karisa",
      authorLastName: "Lacroux",
      description:
          "Dislocation of distal interphalangeal joint of right middle finger",
      date: "10/26/2016",
      categories: "fiction",
      authorGender: "Female",
      authorAge: 60,
      avatar: "https://robohash.org/autemeteligendi.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 47,
      authorFirstName: "Sari",
      authorLastName: "Hiscoe",
      description:
          "Displaced fracture of proximal phalanx of right great toe, subsequent encounter for fracture with nonunion",
      date: "5/16/2006",
      categories: "thriller",
      authorGender: "Female",
      authorAge: 37,
      avatar: "https://robohash.org/quialiquidipsum.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 48,
      authorFirstName: "Jana",
      authorLastName: "Fulbrook",
      description:
          "Primary angle closure without glaucoma damage, unspecified eye",
      date: "5/17/2009",
      categories: "history",
      authorGender: "Female",
      authorAge: 28,
      avatar:
          "https://robohash.org/dolorumcupiditateet.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 49,
      authorFirstName: "Darb",
      authorLastName: "Taylour",
      description:
          "Unspecified atherosclerosis of nonbiological bypass graft(s) of the extremities, other extremity",
      date: "5/5/2011",
      categories: "thriller",
      authorGender: "Female",
      authorAge: 44,
      avatar:
          "https://robohash.org/liberorepellendusvero.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 50,
      authorFirstName: "Rosanne",
      authorLastName: "Pilipets",
      description: "Burn of unspecified degree of elbow",
      date: "2/5/2013",
      categories: "history",
      authorGender: "Female",
      authorAge: 85,
      avatar: "https://robohash.org/abipsaiusto.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 51,
      authorFirstName: "Gallagher",
      authorLastName: "Crudgington",
      description: "Liver disorders in diseases classified elsewhere",
      date: "5/18/2010",
      categories: "history",
      authorGender: "Male",
      authorAge: 96,
      avatar:
          "https://robohash.org/perspiciatisvoluptatemquae.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 52,
      authorFirstName: "Iosep",
      authorLastName: "Moakson",
      description:
          "Primary blast injury of unspecified part of small intestine, subsequent encounter",
      date: "10/4/2013",
      categories: "romance",
      authorGender: "Male",
      authorAge: 13,
      avatar: "https://robohash.org/quiillumid.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 53,
      authorFirstName: "Skelly",
      authorLastName: "Kilford",
      description: "Sezary disease, intrapelvic lymph nodes",
      date: "8/11/2020",
      categories: "utopia",
      authorGender: "Male",
      authorAge: 12,
      avatar: "https://robohash.org/quietsunt.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 54,
      authorFirstName: "Koral",
      authorLastName: "Townley",
      description: "Pityriasis lichenoides chronica",
      date: "10/18/2011",
      categories: "fiction",
      authorGender: "Female",
      authorAge: 43,
      avatar:
          "https://robohash.org/quodtemporeveritatis.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 55,
      authorFirstName: "Clive",
      authorLastName: "Minchindon",
      description: "Acute promyelocytic leukemia, in remission",
      date: "7/28/2014",
      categories: "thriller",
      authorGender: "Male",
      authorAge: 32,
      avatar: "https://robohash.org/utdeseruntsit.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 56,
      authorFirstName: "Osbert",
      authorLastName: "Kitteman",
      description:
          "Unspecified atherosclerosis of nonautologous biological bypass graft(s) of the extremities",
      date: "4/3/2014",
      categories: "romance",
      authorGender: "Male",
      authorAge: 28,
      avatar:
          "https://robohash.org/dolorofficiadolor.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 57,
      authorFirstName: "Rickie",
      authorLastName: "McCrow",
      description:
          "Diabetes mellitus due to underlying condition with mild nonproliferative diabetic retinopathy with macular edema, bilateral",
      date: "3/20/2007",
      categories: "history",
      authorGender: "Female",
      authorAge: 48,
      avatar:
          "https://robohash.org/aperiamadipiscivero.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 58,
      authorFirstName: "Rosaline",
      authorLastName: "Trounson",
      description:
          "Salter-Harris Type II physeal fracture of upper end of right fibula, subsequent encounter for fracture with nonunion",
      date: "5/8/2005",
      categories: "thriller",
      authorGender: "Female",
      authorAge: 26,
      avatar: "https://robohash.org/oditdictaquo.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 59,
      authorFirstName: "Kimberli",
      authorLastName: "Tunmore",
      description:
          "Other intraarticular fracture of lower end of left radius, subsequent encounter for open fracture type I or II with nonunion",
      date: "1/24/2014",
      categories: "mistery",
      authorGender: "Female",
      authorAge: 70,
      avatar: "https://robohash.org/etutnemo.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 60,
      authorFirstName: "Arther",
      authorLastName: "Preece",
      description:
          "Other injury of other muscles, fascia and tendons at shoulder and upper arm level",
      date: "10/22/2000",
      categories: "sci-fi",
      authorGender: "Male",
      authorAge: 49,
      avatar:
          "https://robohash.org/odioidrepudiandae.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 61,
      authorFirstName: "Elias",
      authorLastName: "Delea",
      description: "Nondisplaced midcervical fracture of right femur",
      date: "1/21/2019",
      categories: "fiction",
      authorGender: "Male",
      authorAge: 13,
      avatar:
          "https://robohash.org/doloremtemporibusdolores.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 62,
      authorFirstName: "Bendicty",
      authorLastName: "Aggiss",
      description:
          "Osteopathy in diseases classified elsewhere, unspecified lower leg",
      date: "6/7/2008",
      categories: "thriller",
      authorGender: "Male",
      authorAge: 80,
      avatar:
          "https://robohash.org/etplaceatnesciunt.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 63,
      authorFirstName: "Enriqueta",
      authorLastName: "Turle",
      description: "Punctate keratitis",
      date: "4/3/2005",
      categories: "history",
      authorGender: "Female",
      authorAge: 21,
      avatar:
          "https://robohash.org/impeditaspernaturet.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 64,
      authorFirstName: "George",
      authorLastName: "Diwell",
      description:
          "Disorders of visual pathways in (due to) neoplasm, unspecified side",
      date: "11/2/2015",
      categories: "history",
      authorGender: "Female",
      authorAge: 82,
      avatar:
          "https://robohash.org/molestiaeametquia.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 65,
      authorFirstName: "Blair",
      authorLastName: "Tupie",
      description:
          "Adverse effect of other parasympathomimetics [cholinergics], subsequent encounter",
      date: "4/5/2011",
      categories: "romance",
      authorGender: "Female",
      authorAge: 92,
      avatar: "https://robohash.org/maioresetmaxime.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 66,
      authorFirstName: "Bastian",
      authorLastName: "Huddy",
      description:
          "Minor laceration of right external jugular vein, subsequent encounter",
      date: "2/9/2014",
      categories: "romance",
      authorGender: "Male",
      authorAge: 18,
      avatar:
          "https://robohash.org/pariaturvoluptateset.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 67,
      authorFirstName: "Timmie",
      authorLastName: "Schwant",
      description: "Hesitancy of micturition",
      date: "5/3/2020",
      categories: "utopia",
      authorGender: "Female",
      authorAge: 99,
      avatar:
          "https://robohash.org/etoptioconsequatur.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 68,
      authorFirstName: "Christyna",
      authorLastName: "Wais",
      description: "25 weeks gestation of pregnancy",
      date: "11/10/2003",
      categories: "romance",
      authorGender: "Female",
      authorAge: 57,
      avatar:
          "https://robohash.org/eiusquiaassumenda.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 69,
      authorFirstName: "Kerwin",
      authorLastName: "Roth",
      description:
          "Military operations involving accidental detonation of onboard marine weapons, civilian, subsequent encounter",
      date: "11/27/2014",
      categories: "romance",
      authorGender: "Male",
      authorAge: 71,
      avatar: "https://robohash.org/nostrumquodrerum.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 70,
      authorFirstName: "Clo",
      authorLastName: "Gallymore",
      description: "Neonatal tachycardia",
      date: "7/1/2010",
      categories: "thriller",
      authorGender: "Female",
      authorAge: 80,
      avatar:
          "https://robohash.org/sitdistinctioillo.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 71,
      authorFirstName: "Tisha",
      authorLastName: "Demeter",
      description: "Open bite of left wrist",
      date: "2/27/2009",
      categories: "fiction",
      authorGender: "Female",
      authorAge: 2,
      avatar: "https://robohash.org/quosquiaet.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 72,
      authorFirstName: "Kaine",
      authorLastName: "Large",
      description:
          "Burn of unspecified degree of abdominal wall, initial encounter",
      date: "9/10/2008",
      categories: "mistery",
      authorGender: "Male",
      authorAge: 64,
      avatar: "https://robohash.org/sitsimiliquemodi.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 73,
      authorFirstName: "Viva",
      authorLastName: "Hamshaw",
      description:
          "Toxic effect of venom of other venomous lizard, undetermined, sequela",
      date: "9/12/2016",
      categories: "romance",
      authorGender: "Female",
      authorAge: 33,
      avatar: "https://robohash.org/autetamet.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 74,
      authorFirstName: "Julee",
      authorLastName: "Deackes",
      description:
          "Chronic multifocal osteomyelitis, unspecified ankle and foot",
      date: "3/3/2020",
      categories: "sci-fi",
      authorGender: "Female",
      authorAge: 84,
      avatar:
          "https://robohash.org/nobisassumendanisi.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 75,
      authorFirstName: "Lorrin",
      authorLastName: "Pesterfield",
      description: "Unspecified injury of bronchus, unspecified",
      date: "3/19/2011",
      categories: "thriller",
      authorGender: "Female",
      authorAge: 6,
      avatar: "https://robohash.org/eaaliquidaut.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 76,
      authorFirstName: "Pierce",
      authorLastName: "Doveston",
      description:
          "Person on outside of pick-up truck or van injured in collision with two- or three-wheeled motor vehicle in nontraffic accident, initial encounter",
      date: "7/26/2001",
      categories: "utopia",
      authorGender: "Male",
      authorAge: 31,
      avatar:
          "https://robohash.org/necessitatibusquisquamiste.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 77,
      authorFirstName: "Mellisent",
      authorLastName: "Sneesby",
      description:
          "Open bite of other finger with damage to nail, initial encounter",
      date: "5/18/2004",
      categories: "mistery",
      authorGender: "Female",
      authorAge: 67,
      avatar: "https://robohash.org/ipsumetrerum.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 78,
      authorFirstName: "Karol",
      authorLastName: "Hutchinson",
      description:
          "Toxic effect of lacrimogenic gas, accidental (unintentional), subsequent encounter",
      date: "10/22/2006",
      categories: "thriller",
      authorGender: "Female",
      authorAge: 99,
      avatar:
          "https://robohash.org/doloresplaceatquis.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 79,
      authorFirstName: "Dael",
      authorLastName: "Bottrill",
      description: "Preterm labor",
      date: "10/2/2008",
      categories: "thriller",
      authorGender: "Male",
      authorAge: 64,
      avatar:
          "https://robohash.org/autemperferendisut.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 80,
      authorFirstName: "Raynard",
      authorLastName: "Errigo",
      description:
          "Displaced fracture of neck of scapula, right shoulder, subsequent encounter for fracture with nonunion",
      date: "7/9/2018",
      categories: "history",
      authorGender: "Male",
      authorAge: 32,
      avatar:
          "https://robohash.org/nihillaudantiumet.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 81,
      authorFirstName: "Tadeas",
      authorLastName: "MacMenamin",
      description:
          "Maxillary fracture, left side, initial encounter for open fracture",
      date: "9/4/2004",
      categories: "history",
      authorGender: "Male",
      authorAge: 32,
      avatar: "https://robohash.org/quisquamnamest.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 82,
      authorFirstName: "Jada",
      authorLastName: "McMickan",
      description: "Other acute osteomyelitis, left tibia and fibula",
      date: "8/8/2016",
      categories: "romance",
      authorGender: "Female",
      authorAge: 87,
      avatar:
          "https://robohash.org/veldeseruntdebitis.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 83,
      authorFirstName: "Brooke",
      authorLastName: "Lassetter",
      description: "Essential (hemorrhagic) thrombocythemia",
      date: "5/23/2009",
      categories: "mistery",
      authorGender: "Male",
      authorAge: 98,
      avatar: "https://robohash.org/eumquasmagni.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 84,
      authorFirstName: "Keefer",
      authorLastName: "Kreutzer",
      description:
          "Displaced fracture of lesser trochanter of left femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing",
      date: "7/10/2012",
      categories: "romance",
      authorGender: "Male",
      authorAge: 70,
      avatar: "https://robohash.org/nesciuntnemoaut.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 85,
      authorFirstName: "Celestyn",
      authorLastName: "Isaaksohn",
      description: "Unspecified viral infection of central nervous system",
      date: "10/14/2017",
      categories: "fiction",
      authorGender: "Female",
      authorAge: 76,
      avatar:
          "https://robohash.org/utenimdignissimos.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 86,
      authorFirstName: "Nert",
      authorLastName: "Soule",
      description:
          "Myelodysplastic syndrome with isolated del(5q) chromosomal abnormality",
      date: "10/8/2013",
      categories: "fiction",
      authorGender: "Female",
      authorAge: 78,
      avatar: "https://robohash.org/utdictahic.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 87,
      authorFirstName: "Mellisent",
      authorLastName: "Caudell",
      description:
          "Bent bone of left ulna, initial encounter for open fracture type I or II",
      date: "12/6/2012",
      categories: "fiction",
      authorGender: "Female",
      authorAge: 40,
      avatar:
          "https://robohash.org/voluptatemvoluptasaccusantium.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 88,
      authorFirstName: "Garry",
      authorLastName: "Narracott",
      description: "Idiopathic gout, right wrist",
      date: "3/27/2009",
      categories: "thriller",
      authorGender: "Male",
      authorAge: 4,
      avatar: "https://robohash.org/nonrerumvel.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 89,
      authorFirstName: "Starlene",
      authorLastName: "Raitt",
      description:
          "Laceration of other specified muscles, fascia and tendons at thigh level, unspecified thigh",
      date: "5/14/2004",
      categories: "sci-fi",
      authorGender: "Female",
      authorAge: 94,
      avatar:
          "https://robohash.org/perferendisquostemporibus.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 90,
      authorFirstName: "Gwendolen",
      authorLastName: "Trytsman",
      description:
          "Other scooter (nonmotorized) accident, subsequent encounter",
      date: "9/12/2005",
      categories: "romance",
      authorGender: "Female",
      authorAge: 24,
      avatar: "https://robohash.org/optioestofficiis.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 91,
      authorFirstName: "Torin",
      authorLastName: "Barnard",
      description:
          "Poisoning by mineralocorticoids and their antagonists, accidental (unintentional)",
      date: "11/15/2002",
      categories: "history",
      authorGender: "Male",
      authorAge: 30,
      avatar:
          "https://robohash.org/voluptatibusconsequaturdolores.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 92,
      authorFirstName: "Beverie",
      authorLastName: "Dosdale",
      description: "Impingement syndrome of right shoulder",
      date: "8/12/2001",
      categories: "romance",
      authorGender: "Female",
      authorAge: 14,
      avatar:
          "https://robohash.org/voluptatumaliquidenim.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 93,
      authorFirstName: "Roxana",
      authorLastName: "Delgaty",
      description: "Algoneurodystrophy, unspecified shoulder",
      date: "2/28/2004",
      categories: "utopia",
      authorGender: "Female",
      authorAge: 3,
      avatar:
          "https://robohash.org/recusandaealiaseum.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 94,
      authorFirstName: "Ursula",
      authorLastName: "Mum",
      description:
          "Spondylosis without myelopathy or radiculopathy, lumbosacral region",
      date: "9/15/2012",
      categories: "thriller",
      authorGender: "Female",
      authorAge: 90,
      avatar:
          "https://robohash.org/seddignissimossint.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 95,
      authorFirstName: "Saidee",
      authorLastName: "Pincked",
      description:
          "Legal intervention involving other explosives, law enforcement official injured, subsequent encounter",
      date: "6/14/2005",
      categories: "utopia",
      authorGender: "Female",
      authorAge: 14,
      avatar:
          "https://robohash.org/recusandaealiasqui.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 96,
      authorFirstName: "Evin",
      authorLastName: "Beartup",
      description:
          "Driver of pick-up truck or van injured in collision with fixed or stationary object in traffic accident",
      date: "2/8/2016",
      categories: "sci-fi",
      authorGender: "Male",
      authorAge: 34,
      avatar:
          "https://robohash.org/explicabodoloreos.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 97,
      authorFirstName: "Romonda",
      authorLastName: "Le Grand",
      description: "Open bite of right wrist, subsequent encounter",
      date: "2/16/2005",
      categories: "history",
      authorGender: "Female",
      authorAge: 73,
      avatar:
          "https://robohash.org/cumqueasperioresdignissimos.png?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 98,
      authorFirstName: "Natalya",
      authorLastName: "Malicki",
      description: "Intraoperative cardiac arrest",
      date: "7/24/2010",
      categories: "history",
      authorGender: "Female",
      authorAge: 47,
      avatar: "https://robohash.org/quiautin.bmp?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 99,
      authorFirstName: "Dorie",
      authorLastName: "Ricard",
      description:
          "Other specified injury of unspecified vertebral artery, initial encounter",
      date: "1/2/2017",
      categories: "mistery",
      authorGender: "Female",
      authorAge: 45,
      avatar: "https://robohash.org/laboretemporeut.jpg?size=150x150&set=set1",
      isFavorite: false,
    ),
    Book(
      id: 100,
      authorFirstName: "Byrle",
      authorLastName: "Dewicke",
      description:
          "Crushing injury of left middle finger, subsequent encounter",
      date: "4/11/2010",
      categories: "utopia",
      authorGender: "Male",
      authorAge: 75,
      avatar:
          "https://robohash.org/consecteturquireprehenderit.png?size=150x150&set=set1",
      isFavorite: false,
    ),
  ];
}
